### PR TITLE
Upgrade to Craft 3

### PR DESCRIPTION
**Pull request by Radiergummi**
This is a starting point for #3... I refactored most of the code to work with Craft 3, though I currently have an issue with the actions, but that should work out somehow I think.  
Take a look at the code - it can be installed just fine already 😊

### CODE REVIEW

**Comment by mattstein** [comment]
Thank you @Radiergummi. We've been working at the same time, I started fresh in a different repo. I should have time to compare both and keep moving next week.

**Comment by Radiergummi** [comment]
👌

**Comment by mattstein** [comment]
FYI, finally finished my first draft [here](https://gitlab.com/workingconcept/cloudflare-craft3-plugin). Not to be a jerk, but because I wanted to have a go at it and learn. I can already see your widget overhaul uses vastly better JavaScript and that our formatting preferences are slightly different. I'll go everything in detail next week and try to consolidate all the fun into one plugin.

Thanks for the nudge and all your work on this. You're way quicker, and _du sprichst das deutsche_!

**Comment by Radiergummi** [comment]
Hey @mattstein, no worries! 😉  
Same for me, I learned a ton while working on my draft, that's why I started this in the first place. Feel free to drop my formatting over board, that's just personal taste... PhpStorm auto formats all my code on save, but I could write up an `.editorconfig` file to keep things in style.  
Thank *you* for the plugin, I'm exited what it looks like in the end!  

*By the way, where would you pick up german in Seattle?*

**Comment by mattstein** [comment]
@Radiergummi Some specific pub menus, but most Google Translate and DuoLingo. I only know a few words and phrases, really. I should get serious with my own auto-formatting; I've recently started entertaining spaces (vs. tabs) and my whole world is upside-down.

More soon.

**Comment by Radiergummi** [comment]
Well I can only recommend [PhpStorm](https://www.jetbrains.com/phpstorm/)... there's autocomplete for anything, I don't really type anything out anymore. Getters/setters or docblocks can be automatically generated, native composer/npm/docker integration and so on.. It's just magic!

**Comment by Radiergummi** [comment]
Hey Matt, how are you doing? Have you had any time to look at the plugin? 😄

**Comment by mattstein** [comment]
I’m sorry for the delay, @Radiergummi, I’ve been sick for almost two weeks and I’ve spent limited time working. Feeling better and should be able to catch up again in a few days!

**Comment by Radiergummi** [comment]
No worries, get well soon.

**Comment by mattstein** [comment]
Hey @Radiergummi, I've finally been through every line and I'm prepared to annoy you with questions! First of all, thanks again for working through everything, improving exception handling, and generally tightening things up. I learned from your work that `Craft::trace()` is a thing, that translations should use the plugin scope, and that the JavaScript can be cleaner and less jQuery-dependent.

My unfinished work is [over here for now](https://gitlab.com/workingconcept/cloudflare-craft3-plugin) and I intend to publish it as a new GitHub repository when it's ready, but I didn't want to delay any further. Please don't be too offended by the broken or dumb stuff, and feel free to identify anything bothersome!

## First, the things I did on purpose:

1. Added a migration for the rules database table.
2. Put `rules()` in the settings model because I expect validation should still be defined someplace—not sure if this is it.
3. Specified database columns for RuleRecord.
4. Replaced `mattstein` namespace declarations with `workingconcept`, set version at `1.0.0` even though it's not ready to be published as 1.0.0 just yet.
5. Kept the `$isConfigured` property on the service because it prevents errors during initial setup before credentials are added.

## Questions

1. Is there a reason you [explicitly register controller actions](https://github.com/Radiergummi/cloudflare-craft-plugin/blob/2396ae369a4e130e4f8faa8a27221289ae757020/src/Cloudflare.php#L84-L93) when they appear to work without being registered here?
2. Is there a reason you grouped AssetBundles in `resources/`? I used the pluginfactory.io scaffold which gave me `assetbundles/`, though I don't think it makes any difference.
3. Did you have a specific reason for specifying request headers [in each call](https://github.com/Radiergummi/cloudflare-craft-plugin/blob/2396ae369a4e130e4f8faa8a27221289ae757020/src/services/CloudflareService.php#L71-L74) as opposed to setting them [once for the client](https://gitlab.com/workingconcept/cloudflare-craft3-plugin/blob/master/src/services/CloudflareService.php#L70-80)? Just about all your code is tidier so this had me puzzled.
4. At risk of embarrassment, is there a significant difference between `RuleRecord::find()->all()`/`RuleRecord::model()->findAll()` and `RuleRecord::deleteAll()`/`RuleRecord::model()->deleteAll()`?
5. Your CloudflareService try/catch blocks are neater, but do you know if RequestExceptions include Cloudflare responses for things like being _unable_ to purge a URL? I know my uglier logic handled those situations gracefully, and I just want to be sure your cleaner work does as well.
6. A final and really basic question: why do you sometimes `Craft::trace('foo', __METHOD__)` vs. `Craft::trace('foo', 'cloudflare')`? I understand that the latter is identifying the message with the plugin scope, but I don't know what the former is doing or why you choose it specifically.

**Comment by mattstein** [comment]
I just finished ironing all the lumps out of [my GitLab version](https://gitlab.com/workingconcept/cloudflare-craft3-plugin) and tested everything, so it should be fully functional if you want to poke at it!

**Comment by Radiergummi** [comment]
Hey @mattstein!  
I'm going to take a deeper look at the code during the holidays, this is just the questions for now:

1. I fought a tough fight with the controller actions, seems like I made some rookie mistake somewhere. I just couldn't get them to work properly. I'd still favor defining them explicitly, simply for convenience: If I'm unsure what actions there are, I can just take a look at the plugin class.  
  On the other hand, that wouldn't be necessary if we had quality documentation, I'm putting that to my 
notes.
2. Not really - I just started with Craft and didn't know about `pluginfactory.io` initially, so I just looked at the  [Plugin list](https://plugins.craftcms.com/) and took notes on how things work from the plugins listed there. Sticking to convention is definitely better!
3. Nope. I just migrated the original code to the new syntax, using client defaults is way better :)
4. Honestly, I have no idea. I didn't really touch the `RuleRecord`s yet, since I was unsure about what they actually do and wanted to ask you first.
5. Well I know that responses don't have the `isSuccessful` method anymore because Guzzle's `RequestException` is thrown for connection errors and non-2xx response codes instantly. Would be a good idea to check for the `errors` property on the response maybe?
6. I've seen you can use the `__METHOD__` to give a reference on where the trace originates from (pluginfactory does that too for the startup log line). But that should be a third parameter afaik.  I *think* I didn't mess that up, but I'm not sure 😅 

All in all, apologies for the unfinished code, it would have required a little more polishing before committing... Thank you for all that work,  I'll make sure to test the plugin and get back to you!

**Comment by mattstein** [comment]
Thanks for the quick reply, @Radiergummi. And no need to apologize for any rough edges, we're all learning here and I'm grateful for any help/perspective.

I also struggled for a while getting controller actions to work everywhere—and should mention that if you update the static action URLs (or anything hardcoded in the Settings model) you also have to be sure the serialized array in the database gets updated too. I burned a fair amount of time figuring that out even though it's pretty much like Craft 2. Agreed on documenting well!

All this "rules" business is very simple, just a quick/rough feature that lets you pick a URL pattern to watch for and purge another one automatically. Example: if you're caching an entire site (including HTML), you may want changes to any detail page (`blog/*`) to clear the cached index page `blog`. You'd visit /admin/cloudflare/rules and edit the table to make this happen. The rules work, they're just very simple and they live in a secret place—and they should probably have a switch to enable them looking at the logic that responds to `EVENT_AFTER_SAVE_ELEMENT` and `EVENT_AFTER_DELETE_ELEMENT`. The whole approach could be smarter, but this should at least explain what the RuleRecord and database table are for.

I updated Craft's traces to specifically list any URLs cleared, which should make testing easier. In the logs, you'll see an ID that can only come from Cloudflare (enough confirmation for me that a cache was cleared) along with the URLs that were passed along to be purged. I miss having the plugin-specific log (cloudflare.log vs. digging through web.log), not that it's a huge deal.

I think this is all getting much closer, and I'm eager to see how your testing goes. Cheers! 🎄

**Comment by Radiergummi** [comment]
Hey Matt,

I'm sorry for not having replied that long, the last few weeks have been pretty busy, but rest assured I'm still on this and going to install the plugin on the client site soon!

**Comment by mattstein** [comment]
Nice hearing from you @Radiergummi, and no need to rush or apologize. I'll look forward to your feedback whenever you get around to it.

**Comment by Radiergummi** [comment]
So I finally came around installing the plugin on the Craft site (it'll go live on friday, so that was due for sure). I noticed some script errors for the validate credentials button, otherwise it seems to work fine so far, including the individual purge and the widget! I'm going to take a look at the JavaScript but other than that the plugin looks ready for the store to me! 😊

**Comment by Radiergummi** [comment]
Hah, just discovered an issue - if the URL to be purged can't be found, Cloudflare will trigger a `400`. These result in response exceptions not being catched and shown to the user.

**Comment by mattstein** [comment]
Thanks for mentioning it @Radiergummi, and sorry for my slow response here. I'll see if I can find a little time to fix by next week.

**Comment by mattstein** [comment]
Hi again @Radiergummi! Just fixed those validation errors and started catching (and logging) Cloudflare's 400 errors in this repo's master branch: https://gitlab.com/workingconcept/craft-cloudflare. Can you let me know if this works for you?

**Comment by Radiergummi** [comment]
Hi Matt, I just [deployed](https://www.museum-muenchen.de/) the site I was working on including Cloudflare, yay!  
I'm going to let the dust settle a bit and update the plugin the next days, but judging from the code it looks gorgeous, thank you. I'll be reporting!

**Comment by mattstein** [comment]
Done with e78a2cfe451d74a2cff71af84be091f8eaf23886. Thanks for all the help @Radiergummi!

**Comment by Radiergummi** [comment]
Was a pleasure working with you! 😄

**Pull request closed without merging**
