### PR TITLE
Adds a widget to the dashboard

### PR DESCRIPTION
**Pull request by Radiergummi**
As promised, here's the (surprisingly small) widget PR as mentioned in #1 . Please note however that this is the first time I got my hands on Craft plugins, so maybe I made some rookie errors.  
It would be nice to display a success message after purge, or a zone selector.

### CODE REVIEW

**Comment by mattstein** [comment]
Thanks for submitting this, @Radiergummi! Would you mind if I merged this into a branch and made a few adjustments? I'd like to work confirmation messages in like you've pointed out, and maybe spiff up the widget UI to visually separate a global purge from individual URLs.

**Comment by Radiergummi** [comment]
I definitely don't mind, I'm happy if those few lines of poorly cobbled-together code provide you with a starting point 😄

**Comment by mattstein** [comment]
@Radiergummi, I appreciate your jump-start here and just merged your work in with some updates (mostly cosmetic) called out in 492ad92595310216bb81f4d1f50013482538017c. Let me know if you've got an issues or objections!

**Comment by Radiergummi** [comment]
It's gorgeous. Thank you 😄

**Pull request merged**
